services:
  - type: web
    name: dexoppo-backend
    runtime: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
    healthCheckPath: /health
    rootDir: backend