name: Deploy Backend to Fly.io

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: superfly/flyctl-actions/setup-flyctl@master
    
    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      working-directory: backend
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        FLY_APP: ${{ secrets.FLY_APP }}